<div class="container"><h4>throw_exception/1</h4><pre><code>throw_exception(+Exception)</code></pre><p>This predicate throws the exception +Exception.</p></div>
<div class="container"><h4>instantiation_error/2</h4><pre><code>instantiation_error(+Indicator, ?Error)</code></pre><p>This predicate succeeds when ?Error is the instantiation error produced by the predicate +Indicator. This error is produced when an argument or one of its components is a variable, and an instantiated argument or component is required.</p></div>
<div class="container"><h4>type_error/4</h4><pre><code>type_error(+Type, +Term, +Indicator, ?Error)</code></pre><p>This predicate succeeds when ?Error is the type error produced by the type +Type of the term +Term in the predicate +Indicator. This error is produced when the type of an argument or of one of its components is incorrect, but not a variable.</p></div>
<div class="container"><h4>evaluation_error/3</h4><pre><code>evaluation_error(+Cause, +Indicator, ?Error)</code></pre><p>This predicate succeeds when ?Error is the evaluation error produced by the cause +Cause in the predicate +Indicator. This error is produced when the operands of an evaluable functor has an exceptional value.</p></div>
<div class="container"><h4>existence_error/4</h4><pre><code>existence_error(+Cause, +Term, +Indicator, ?Error)</code></pre><p>This predicate succeeds when ?Error is the existence error produced by the term +Term in the predicate +Indicator. This error is produced when the object on which an operation is to be performed does not exist.</p></div>